# Generated by Django 5.1.15 on 2026-09-17 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('TRIP_DELAYED', 'Trip Delayed'), ('TRIP_UNASSIGNED', 'Trip Needs Assignment'), ('MAINTENANCE_OVERDUE', 'Maintenance Overdue'), ('DOCUMENT_EXPIRED', 'Document Expired'), ('DOCUMENT_EXPIRING', 'Document Expiring Soon')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_archived'], name='alerts_aler_status_a12b74_idx'), models.Index(fields=['content_type', 'object_id'], name='alerts_aler_content_a9e91b_idx')],
            },
        ),
    ]
