# Generated by Django 5.1.15 on 2026-10-03 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('clients', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('drivers', '0001_initial'),
        ('tracking', '0008_vehiclecurrenttelemetry_gps_odometer'),
        ('vehicles', '0005_vehicle_trip_movement_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Owner of the vehicle when the event happened (scoping boundary).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.client'),
        ),
        migrations.AddField(
            model_name='alert',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='alert',
            name='ignition',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_signal_at',
            field=models.DateTimeField(blank=True, help_text='Device time of the latest signal reading.', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='occurred_at',
            field=models.DateTimeField(blank=True, help_text='Device (GPS) time of the first signal.', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='odometer',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='signal_cleared_at',
            field=models.DateTimeField(blank=True, help_text='Device time the signal went back to normal (null = still active).', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='telemetry_event',
            field=models.ForeignKey(blank=True, help_text='The history record that raised the alert.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracking.telemetryevent'),
        ),
        migrations.AddField(
            model_name='alert',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='alert',
            name='voltage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('TRIP_DELAYED', 'Trip Delayed'), ('TRIP_UNASSIGNED', 'Trip Needs Assignment'), ('MAINTENANCE_OVERDUE', 'Maintenance Overdue'), ('DOCUMENT_EXPIRED', 'Document Expired'), ('DOCUMENT_EXPIRING', 'Document Expiring Soon'), ('PANIC', 'Panic')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['vehicle', 'occurred_at'], name='alerts_aler_vehicle_ccabf5_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['client', 'occurred_at'], name='alerts_aler_client__eef914_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['category', 'occurred_at'], name='alerts_aler_categor_785f0e_idx'),
        ),
    ]
