# Generated by Django 5.1.15 on 2026-10-04 06:49

from django.conf import settings
from django.db import migrations, models


def panic_triggered_at(apps, schema_editor):
    """A panic alert is raised the moment the signal starts."""
    Alert = apps.get_model("alerts", "Alert")
    Alert.objects.filter(category="PANIC", triggered_at__isnull=True).update(triggered_at=models.F("occurred_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_vehicle_events'),
        ('clients', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('drivers', '0001_initial'),
        ('tracking', '0008_vehiclecurrenttelemetry_gps_odometer'),
        ('vehicles', '0006_vehicle_idle_alert_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='triggered_at',
            field=models.DateTimeField(blank=True, help_text='Device time the alert condition was met (panic: = occurred_at; idle: the idle threshold reached).', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('TRIP_DELAYED', 'Trip Delayed'), ('TRIP_UNASSIGNED', 'Trip Needs Assignment'), ('MAINTENANCE_OVERDUE', 'Maintenance Overdue'), ('DOCUMENT_EXPIRED', 'Document Expired'), ('DOCUMENT_EXPIRING', 'Document Expiring Soon'), ('PANIC', 'Panic'), ('IDLE', 'Idle')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='alert',
            name='last_signal_at',
            field=models.DateTimeField(blank=True, help_text='Device time of the latest reading still in the condition.', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='occurred_at',
            field=models.DateTimeField(blank=True, help_text='Device (GPS) time the condition began (panic pressed / vehicle went idle).', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='signal_cleared_at',
            field=models.DateTimeField(blank=True, help_text='Device time the condition ended — panic released / vehicle moved or ignition off (null = active).', null=True),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'occurred_at'], name='alerts_aler_severit_347b0c_idx'),
        ),
        migrations.RunPython(panic_triggered_at, migrations.RunPython.noop),
    ]
