# Generated by Django 5.1.15 on 2026-10-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_idle_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('TRIP_DELAYED', 'Trip Delayed'), ('TRIP_UNASSIGNED', 'Trip Needs Assignment'), ('MAINTENANCE_OVERDUE', 'Maintenance Overdue'), ('DOCUMENT_EXPIRED', 'Document Expired'), ('DOCUMENT_EXPIRING', 'Document Expiring Soon'), ('PANIC', 'Panic'), ('IDLE', 'Idle'), ('OVER_SPEEDING', 'Over Speeding')], db_index=True, max_length=30),
        ),
    ]
