# Generated by Django 5.1.15 on 2026-10-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_device_battery_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='speed_limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Geofence Speeding: the geofence's speed limit (km/h) when it was raised.", null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('TRIP_DELAYED', 'Trip Delayed'), ('TRIP_UNASSIGNED', 'Trip Needs Assignment'), ('MAINTENANCE_OVERDUE', 'Maintenance Overdue'), ('DOCUMENT_EXPIRED', 'Document Expired'), ('DOCUMENT_EXPIRING', 'Document Expiring Soon'), ('PANIC', 'Panic'), ('IDLE', 'Idle'), ('OVER_SPEEDING', 'Over Speeding'), ('MAIN_POWER_DISCONNECTED', 'Main Power Disconnected'), ('LOW_VOLTAGE', 'Low Voltage'), ('DEVICE_BATTERY_DISCONNECTED', 'Device Battery Disconnected'), ('DEVICE_BATTERY_LOW_VOLTAGE', 'Device Battery Low Voltage'), ('GEOFENCE_ENTRY', 'Geofence Entry'), ('GEOFENCE_EXIT', 'Geofence Exit'), ('GEOFENCE_SPEEDING', 'Geofence Speeding')], db_index=True, max_length=30),
        ),
    ]
