# Generated by Django 5.1.15 on 2026-08-12 17:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('drivers', '0001_initial'),
        ('locations', '0002_site'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripNumberSequence',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('trip_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('trip_type', models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Pickup'), ('TRANSFER', 'Transfer'), ('ROUND_TRIP', 'Round Trip'), ('OTHER', 'Other')], default='DELIVERY', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ASSIGNED', 'Assigned'), ('DISPATCHED', 'Dispatched'), ('IN_PROGRESS', 'In Progress'), ('DELAYED', 'Delayed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=15)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('planned_distance', models.DecimalField(blank=True, decimal_places=2, help_text='km', max_digits=8, null=True)),
                ('actual_distance', models.DecimalField(blank=True, decimal_places=2, help_text='km', max_digits=8, null=True)),
                ('fuel_used', models.DecimalField(blank=True, decimal_places=2, help_text='litres', max_digits=7, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('driver_remarks', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('delay_reason', models.CharField(blank=True, choices=[('TRAFFIC', 'Traffic'), ('VEHICLE_ISSUE', 'Vehicle Issue'), ('DRIVER_ISSUE', 'Driver Issue'), ('WEATHER', 'Weather'), ('CLIENT_DELAY', 'Client Delay'), ('OTHER', 'Other')], max_length=20)),
                ('delay_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_destination', to='locations.site')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='drivers.driver')),
                ('origin_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_origin', to='locations.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-scheduled_start'],
                'indexes': [models.Index(fields=['trip_number'], name='trips_trip_trip_nu_39e2d9_idx'), models.Index(fields=['status'], name='trips_trip_status_259ca6_idx'), models.Index(fields=['scheduled_start'], name='trips_trip_schedul_359bde_idx')],
            },
        ),
    ]
