# Generated by Django 5.1.15 on 2026-09-17 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Optional — a reusable multi-stop itinerary this trip follows. A trip with no route still works exactly as before, using origin_site/destination_site alone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='routes.route'),
        ),
    ]
