# Generated by Django 5.1.15 on 2026-09-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_permission_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('user', 'User'), ('role', 'Role'), ('client', 'Client'), ('site', 'Client Site'), ('vendor', 'Vendor'), ('branch', 'Branch / Depot'), ('contract', 'Contract'), ('vehicle', 'Vehicle'), ('vehicle_type', 'Vehicle Type'), ('driver', 'Driver'), ('assignment', 'Vehicle-Driver Assignment'), ('document', 'Document'), ('insurance', 'Insurance'), ('tracking_device', 'GPS Device'), ('maintenance', 'Maintenance'), ('route', 'Route'), ('trip', 'Trip'), ('geofence', 'Geofence'), ('alert', 'Alert'), ('notification', 'Notification'), ('master_data', 'Master Data'), ('audit_log', 'Audit Log'), ('report', 'Report'), ('settings', 'Settings')], max_length=30),
        ),
    ]
