# Generated by Django 5.1.15 on 2026-09-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_permission_module'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, help_text="Set for client users: they only ever see this client's data, read-only. Leave empty for internal staff.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='clients.client'),
        ),
    ]
