# Generated by Django 5.1.15 on 2026-09-27 07:18

from django.db import migrations, models


def delete_report_permissions(apps, schema_editor):
    """The "report" module (the Operational Reports hub) no longer exists:
    drop its permissions so no role keeps a grant for a module that isn't
    there. Role grants (RolePermission) go with them via ON DELETE CASCADE.
    Audit-log history that mentions "report" is left untouched."""
    Permission = apps.get_model("accounts", "Permission")
    Permission.objects.filter(module="report").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_client'),
    ]

    operations = [
        # Irreversible by nature (the grants are gone); reversing only restores
        # the schema choice, and seed_roles no longer recreates the module.
        migrations.RunPython(delete_report_permissions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('user', 'User'), ('role', 'Role'), ('client', 'Client'), ('site', 'Client Site'), ('vendor', 'Vendor'), ('branch', 'Branch / Depot'), ('contract', 'Contract'), ('vehicle', 'Vehicle'), ('vehicle_type', 'Vehicle Type'), ('driver', 'Driver'), ('assignment', 'Vehicle-Driver Assignment'), ('document', 'Document'), ('insurance', 'Insurance'), ('tracking_device', 'GPS Device'), ('maintenance', 'Maintenance'), ('route', 'Route'), ('trip', 'Trip'), ('geofence', 'Geofence'), ('alert', 'Alert'), ('notification', 'Notification'), ('master_data', 'Master Data'), ('audit_log', 'Audit Log'), ('settings', 'Settings')], max_length=30),
        ),
    ]
