# Generated by Django 5.1.15 on 2026-09-17 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, help_text='Overrides the default app name shown in the sidebar/browser tab when set.', max_length=150)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('default_timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('default_currency', models.CharField(choices=[('INR', 'Indian Rupee (INR)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('AED', 'UAE Dirham (AED)')], default='INR', max_length=3)),
                ('date_format', models.CharField(choices=[('DMY', 'DD/MM/YYYY'), ('MDY', 'MM/DD/YYYY'), ('YMD', 'YYYY-MM-DD')], default='DMY', max_length=3)),
                ('document_expiry_warning_days', models.PositiveSmallIntegerField(default=30, help_text="Documents expiring within this many days are flagged as 'expiring soon'.")),
                ('maintenance_due_soon_days', models.PositiveSmallIntegerField(default=7, help_text="Scheduled maintenance due within this many days is flagged as 'due soon'.")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
