# Generated by Django 5.1.15 on 2026-08-13 17:24

import apps.core.validators
import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('RC', 'Registration Certificate'), ('INSURANCE', 'Insurance'), ('PUC', 'Pollution Certificate'), ('FITNESS', 'Fitness Certificate'), ('PERMIT', 'Permit'), ('SERVICE_RECORD', 'Service Record'), ('DRIVING_LICENSE', 'Driving License'), ('ID_PROOF', 'ID Proof'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('TRAINING_CERTIFICATE', 'Training Certificate'), ('CONTRACT', 'Contract'), ('AGREEMENT', 'Agreement'), ('TAX_CERTIFICATE', 'Tax Certificate'), ('REGISTRATION', 'Registration'), ('ADDRESS_PROOF', 'Address Proof'), ('TRIP_SHEET', 'Trip Sheet'), ('DELIVERY_PROOF', 'Delivery Proof'), ('INVOICE', 'Invoice'), ('SERVICE_INVOICE', 'Service Invoice'), ('REPAIR_ESTIMATE', 'Repair Estimate'), ('WARRANTY', 'Warranty'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=15)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[apps.core.validators.validate_file_size, apps.core.validators.validate_document_extension, apps.core.validators.validate_document_content])),
                ('original_filename', models.CharField(editable=False, max_length=255)),
                ('file_size', models.PositiveIntegerField(editable=False, help_text='bytes')),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replaces', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_number'], name='documents_d_documen_dbcf06_idx'), models.Index(fields=['content_type', 'object_id'], name='documents_d_content_ba3031_idx'), models.Index(fields=['status'], name='documents_d_status_07369e_idx'), models.Index(fields=['expiry_date'], name='documents_d_expiry__1d702a_idx')],
            },
        ),
    ]
