# Generated by Django 5.1.15 on 2026-08-11 17:04

import apps.core.validators
import apps.vehicles.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contracts', '0001_initial'),
        ('drivers', '0001_initial'),
        ('locations', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Vehicle categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_types', to='vehicles.vehiclecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_code', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='VIN')),
                ('chassis_number', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('engine_number', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=80)),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('variant', models.CharField(blank=True, max_length=80)),
                ('model_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2027)])),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('transmission_type', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic'), ('AMT', 'AMT'), ('CVT', 'CVT')], max_length=15)),
                ('engine_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='cc', max_digits=8, null=True)),
                ('seating_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('load_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=10, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, help_text='km/l', max_digits=6, null=True)),
                ('ownership_type', models.CharField(choices=[('OWNED', 'Owned'), ('LEASED', 'Leased'), ('RENTED', 'Rented'), ('VENDOR_OWNED', 'Vendor-Owned')], default='OWNED', max_length=15)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('ACCIDENT', 'Accident'), ('SOLD', 'Sold'), ('RETIRED', 'Retired'), ('SCRAPPED', 'Scrapped')], db_index=True, default='ACTIVE', max_length=20)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('ON_TRIP', 'On Trip'), ('MAINTENANCE', 'Maintenance'), ('UNAVAILABLE', 'Unavailable')], db_index=True, default='AVAILABLE', max_length=15)),
                ('odometer_reading', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('odometer_unit', models.CharField(choices=[('KM', 'Kilometers'), ('MILES', 'Miles')], default='KM', max_length=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.vehicles.models.vehicle_image_upload_path, validators=[apps.core.validators.validate_file_size, apps.core.validators.validate_image_extension])),
                ('remarks', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='locations.branch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='clients.client')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vehicles', to='drivers.driver')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.fueltype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vendors.vendor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehiclecategory')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehicletype')),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TEMPORARY', 'Temporary'), ('RELIEF', 'Relief')], default='PRIMARY', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('primary_driver', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=15)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='drivers.driver')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['vehicle', 'status'], name='vehicles_ve_vehicle_1fbe97_idx'), models.Index(fields=['driver', 'status'], name='vehicles_ve_driver__5d1674_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('primary_driver', True), ('status', 'ACTIVE')), fields=('vehicle',), name='uniq_active_primary_assignment_per_vehicle')],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration_number'], name='vehicles_ve_registr_3774f3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='vehicles_ve_vin_d8dea1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='vehicles_ve_status_f71f77_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['availability_status'], name='vehicles_ve_availab_5aec56_idx'),
        ),
    ]
