# Generated by Django 5.1.15 on 2026-09-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0002_vehicle_last_service_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='clients.client'),
        ),
    ]
