# Generated by Django 5.1.15 on 2026-09-26 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='trip_closure_minutes',
            field=models.PositiveSmallIntegerField(default=5, help_text='Ignition OFF for this many minutes or more closes the current trip; switching back ON sooner continues the same trip.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Trip closure time (minutes)'),
        ),
    ]
