# Generated by Django 5.1.15 on 2026-10-03 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_trip_closure_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='trip_min_distance_m',
            field=models.PositiveSmallIntegerField(default=50, help_text='How far the vehicle must get from where the ignition came on before a trip is confirmed.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(2000)], verbose_name='Minimum movement distance (m)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trip_min_moving_records',
            field=models.PositiveSmallIntegerField(default=3, help_text='How many of those readings must be at or above the minimum speed.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Required moving records'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trip_min_speed_kmh',
            field=models.PositiveSmallIntegerField(default=5, help_text='A reading at or above this speed counts as moving.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Minimum movement speed (km/h)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trip_validation_records',
            field=models.PositiveSmallIntegerField(default=5, help_text='How many consecutive readings are examined when deciding whether the vehicle is moving.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)], verbose_name='Validation records'),
        ),
    ]
