# Generated by Django 5.1.15 on 2026-10-04 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_trip_movement_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='idle_alert_minutes',
            field=models.PositiveSmallIntegerField(default=5, help_text='Ignition ON and stationary continuously for this long raises an Idle alert.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='Idle alert after (minutes)'),
        ),
    ]
