# Generated by Django 5.1.15 on 2026-08-13 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_vehicle_last_service_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceNumberSequence',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('maintenance_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('INSPECTION', 'Inspection'), ('REPAIR', 'Repair'), ('OIL_SERVICE', 'Oil Service'), ('TYRE_SERVICE', 'Tyre Service'), ('BRAKE_SERVICE', 'Brake Service'), ('ELECTRICAL', 'Electrical'), ('OTHER', 'Other')], default='PREVENTIVE', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('scheduled_date', models.DateField()),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('odometer_at_service', models.DecimalField(decimal_places=1, max_digits=10)),
                ('next_service_odometer', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('service_center', models.CharField(blank=True, max_length=150)),
                ('technician', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('work_performed', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Maintenance records',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_name', models.CharField(max_length=150)),
                ('part_number', models.CharField(blank=True, max_length=60)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='maintenance.maintenance')),
            ],
            options={
                'ordering': ['part_name'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['maintenance_number'], name='maintenance_mainten_5eec2d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['status'], name='maintenance_status_a1de4d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['scheduled_date'], name='maintenance_schedul_df169e_idx'),
        ),
    ]
