from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from apps.core.models import TimeStampedModel, UUIDModel


class Alert(UUIDModel, TimeStampedModel):
    """A persisted, actionable operational condition — the durable form of
    what apps.core.dashboard_services.OperationsService.attention_items()
    already computes ad hoc for the Dashboard. The two stay independent on
    purpose: the Dashboard's panel is a cheap, always-fresh read-only
    summary; Alert is the workflow record (acknowledge/resolve/archive,
    with an audit trail) for whoever owns the "alert" RBAC module.

    No ``create`` action in the RBAC catalog for this module — alerts are
    never hand-authored, only generated by ``apps.alerts.services.sync_alerts``
    from real conditions (delayed trips, overdue maintenance, expired/
    expiring documents), then acknowledged/resolved/archived by a human.

    ``dedupe_key`` is what makes sync idempotent: re-running it while a
    condition still holds updates the same row instead of creating a
    duplicate open alert every time.

    Vehicle (telemetry) alerts — ``TELEMETRY_CATEGORIES``: PANIC (CRITICAL) and
    IDLE (MEDIUM), OVER_SPEEDING (HIGH, apps.alerts.overspeed: the device's
    eventioval 255 start/end records), MAIN_POWER_DISCONNECTED (HIGH, main
    power < 5 V), LOW_VOLTAGE (MEDIUM, 5 V to < 8.5 V) and the device battery's
    DEVICE_BATTERY_DISCONNECTED (HIGH, < 2 V) / DEVICE_BATTERY_LOW_VOLTAGE
    (MEDIUM, 2 V to < 3 V) — the voltage alerts on the same engine as panic —
    and GEOFENCE_ENTRY / GEOFENCE_EXIT (MEDIUM) and GEOFENCE_SPEEDING (HIGH)
    from apps.geofences.services, whose geofence is the ``content_object`` — are EVENTS raised from the GPS
    history, one row per episode: apps.alerts.events (panic: 0 -> 1 starts it, further 1s belong to
    it, 1 -> 0 clears it) and apps.alerts.idle (ignition ON and stationary for
    the vehicle's idle threshold; ends when it moves or the ignition goes off). They carry the vehicle, the client who owned it at the
    time (the tenant boundary for scoping, like TelemetryEvent.client), the
    driver, and a snapshot of the reading that raised them. ``status`` is the
    human workflow (Open = new, Acknowledged, Resolved) and is independent of
    ``signal_cleared_at`` (the device stopped signalling). The Alert Report,
    the bell notification and both exports all read these rows — nothing else
    re-detects an alert.
    """

    class Severity(models.TextChoices):
        LOW = "LOW", "Low"
        MEDIUM = "MEDIUM", "Medium"
        HIGH = "HIGH", "High"
        CRITICAL = "CRITICAL", "Critical"

    class Category(models.TextChoices):
        TRIP_DELAYED = "TRIP_DELAYED", "Trip Delayed"
        TRIP_UNASSIGNED = "TRIP_UNASSIGNED", "Trip Needs Assignment"
        MAINTENANCE_OVERDUE = "MAINTENANCE_OVERDUE", "Maintenance Overdue"
        DOCUMENT_EXPIRED = "DOCUMENT_EXPIRED", "Document Expired"
        DOCUMENT_EXPIRING = "DOCUMENT_EXPIRING", "Document Expiring Soon"
        # Vehicle telemetry events (apps.alerts.events). A new type = one choice
        # here + its detector there; the report/exports/bell need no change.
        PANIC = "PANIC", "Panic"
        IDLE = "IDLE", "Idle"
        OVER_SPEEDING = "OVER_SPEEDING", "Over Speeding"
        MAIN_POWER_DISCONNECTED = "MAIN_POWER_DISCONNECTED", "Main Power Disconnected"
        LOW_VOLTAGE = "LOW_VOLTAGE", "Low Voltage"
        DEVICE_BATTERY_DISCONNECTED = "DEVICE_BATTERY_DISCONNECTED", "Device Battery Disconnected"
        DEVICE_BATTERY_LOW_VOLTAGE = "DEVICE_BATTERY_LOW_VOLTAGE", "Device Battery Low Voltage"
        # Geofence events (apps.geofences.services); the geofence is the alert's content_object.
        GEOFENCE_ENTRY = "GEOFENCE_ENTRY", "Geofence Entry"
        GEOFENCE_EXIT = "GEOFENCE_EXIT", "Geofence Exit"
        GEOFENCE_SPEEDING = "GEOFENCE_SPEEDING", "Geofence Speeding"

    class Status(models.TextChoices):
        OPEN = "OPEN", "Open"
        ACKNOWLEDGED = "ACKNOWLEDGED", "Acknowledged"
        RESOLVED = "RESOLVED", "Resolved"

    dedupe_key = models.CharField(max_length=255, unique=True)
    category = models.CharField(max_length=30, choices=Category.choices, db_index=True)
    severity = models.CharField(max_length=10, choices=Severity.choices, db_index=True)
    status = models.CharField(max_length=15, choices=Status.choices, default=Status.OPEN, db_index=True)

    title = models.CharField(max_length=200)
    message = models.CharField(max_length=500, blank=True)
    link_url = models.CharField(max_length=300, blank=True)

    content_type = models.ForeignKey(ContentType, null=True, blank=True, on_delete=models.CASCADE)
    object_id = models.PositiveBigIntegerField(null=True, blank=True)
    content_object = GenericForeignKey("content_type", "object_id")

    is_archived = models.BooleanField(default=False, db_index=True)

    acknowledged_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL, related_name="+"
    )
    acknowledged_at = models.DateTimeField(null=True, blank=True)
    resolved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL, related_name="+"
    )
    resolved_at = models.DateTimeField(null=True, blank=True)

    # --- Vehicle telemetry events (empty for operational alerts) ---
    vehicle = models.ForeignKey(
        "vehicles.Vehicle", null=True, blank=True, on_delete=models.SET_NULL, related_name="alerts"
    )
    client = models.ForeignKey(
        "clients.Client", null=True, blank=True, on_delete=models.SET_NULL, related_name="+",
        help_text="Owner of the vehicle when the event happened (scoping boundary).",
    )
    driver = models.ForeignKey("drivers.Driver", null=True, blank=True, on_delete=models.SET_NULL, related_name="+")
    occurred_at = models.DateTimeField(
        null=True, blank=True, help_text="Device (GPS) time the condition began (panic pressed / vehicle went idle)."
    )
    triggered_at = models.DateTimeField(
        null=True, blank=True,
        help_text="Device time the alert condition was met (panic: = occurred_at; idle: the idle threshold reached).",
    )
    last_signal_at = models.DateTimeField(
        null=True, blank=True, help_text="Device time of the latest reading still in the condition."
    )
    signal_cleared_at = models.DateTimeField(
        null=True, blank=True,
        help_text="Device time the condition ended — panic released / vehicle moved or ignition off (null = active).",
    )
    telemetry_event = models.ForeignKey(
        "tracking.TelemetryEvent", null=True, blank=True, on_delete=models.SET_NULL, related_name="+",
        help_text="The history record that raised the alert.",
    )
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    location = models.CharField(max_length=255, blank=True, default="")
    speed = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    ignition = models.BooleanField(null=True, blank=True)
    odometer = models.DecimalField(max_digits=10, decimal_places=1, null=True, blank=True)
    voltage = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    speed_limit = models.PositiveSmallIntegerField(
        null=True, blank=True, help_text="Geofence Speeding: the geofence's speed limit (km/h) when it was raised.",
    )

    TELEMETRY_CATEGORIES = (
        Category.PANIC, Category.IDLE, Category.OVER_SPEEDING, Category.MAIN_POWER_DISCONNECTED, Category.LOW_VOLTAGE,
        Category.DEVICE_BATTERY_DISCONNECTED, Category.DEVICE_BATTERY_LOW_VOLTAGE,
        Category.GEOFENCE_ENTRY, Category.GEOFENCE_EXIT, Category.GEOFENCE_SPEEDING,
    )

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["status", "is_archived"]),
            models.Index(fields=["content_type", "object_id"]),
            models.Index(fields=["vehicle", "occurred_at"]),
            models.Index(fields=["client", "occurred_at"]),
            models.Index(fields=["category", "occurred_at"]),
            models.Index(fields=["severity", "occurred_at"]),
        ]

    def __str__(self):
        return self.title
