# Generated by Django 5.1.15 on 2026-08-11 17:04

import apps.core.validators
import apps.drivers.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('locations', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNDISCLOSED', 'Prefer not to say')], max_length=15)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=apps.drivers.models.driver_photo_upload_path, validators=[apps.core.validators.validate_file_size, apps.core.validators.validate_image_extension])),
                ('mobile_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (7-15 digits, optional leading +).', regex='^\\+?[0-9]{7,15}$')])),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (7-15 digits, optional leading +).', regex='^\\+?[0-9]{7,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid postal/pin code.', regex='^[0-9A-Za-z\\- ]{4,10}$')])),
                ('driver_type', models.CharField(choices=[('COMPANY', 'Company Driver'), ('CONTRACT', 'Contract Driver'), ('OWNER_OPERATOR', 'Owner-Operator')], default='COMPANY', max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=15)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=15)),
                ('license_number', models.CharField(max_length=40, unique=True)),
                ('license_type', models.CharField(blank=True, max_length=60)),
                ('license_issue_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=120)),
                ('issuing_state', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=16)),
                ('preferred_shift', models.CharField(blank=True, choices=[('DAY', 'Day'), ('NIGHT', 'Night'), ('ROTATING', 'Rotating')], max_length=10)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='locations.branch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='vendors.vendor')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['employee_id'], name='drivers_dri_employe_695e9f_idx'), models.Index(fields=['license_number'], name='drivers_dri_license_ce5f7e_idx'), models.Index(fields=['employment_status'], name='drivers_dri_employm_bfbbe0_idx')],
            },
        ),
    ]
