# Generated by Django 5.1.15 on 2026-08-08 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ARCHIVE', 'Archive'), ('RESTORE', 'Restore'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ASSIGN', 'Assign'), ('UNASSIGN', 'Unassign'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('EXPORT', 'Export')], db_index=True, max_length=20)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('entity', models.CharField(help_text="Model name the action applied to, e.g. 'User'.", max_length=100)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for system-initiated actions (e.g. scheduled jobs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', 'entity', 'entity_id'], name='audit_audit_module_76f37a_idx'), models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx')],
            },
        ),
    ]
