# Generated by Django 5.1.15 on 2026-08-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ARCHIVE', 'Archive'), ('RESTORE', 'Restore'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ASSIGN', 'Assign'), ('UNASSIGN', 'Unassign'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('EXPORT', 'Export'), ('DISPATCH', 'Dispatch'), ('START', 'Start'), ('DELAY', 'Delay'), ('RESUME', 'Resume'), ('COMPLETE', 'Complete'), ('CANCEL', 'Cancel'), ('DELETE', 'Delete'), ('DOWNLOAD', 'Download')], db_index=True, max_length=20),
        ),
    ]
