# Generated by Django 5.1.15 on 2026-08-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        ('vehicles', '0002_vehicle_last_service_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdevice',
            name='firmware_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trackingdevice',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='trackingdevice',
            name='provider',
            field=models.CharField(choices=[('generic', 'Generic JSON'), ('teltonika', 'Teltonika'), ('mdvr', 'MDVR'), ('navtelecom', 'NavTelecom'), ('other', 'Other')], db_index=True, default='generic', max_length=20),
        ),
        migrations.AddField(
            model_name='trackingdevice',
            name='secret_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='VehicleCurrentTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ignition', models.BooleanField(blank=True, null=True)),
                ('odometer', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracking.trackingdevice')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_telemetry', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Vehicle current telemetry',
            },
        ),
        migrations.CreateModel(
            name='RawTelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='Snapshot of device.provider at ingest time.', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', models.JSONField()),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('PARTIAL', 'Partially Processed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_events', to='tracking.trackingdevice')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['device', 'received_at'], name='tracking_ra_device__3cf4b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Device/event time (distinct from received_at).')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='km/h', max_digits=6, null=True)),
                ('heading', models.PositiveSmallIntegerField(blank=True, help_text='Degrees, 0-359.', null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Metres.', max_digits=7, null=True)),
                ('ignition', models.BooleanField(blank=True, null=True)),
                ('odometer', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('engine_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('external_power', models.BooleanField(blank=True, null=True)),
                ('signal_strength', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('satellite_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Provider-specific extra fields.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telemetry_events', to='tracking.trackingdevice')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_events', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='tracking_te_device__2a6531_idx'), models.Index(fields=['vehicle', 'timestamp'], name='tracking_te_vehicle_e9872c_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'timestamp', 'latitude', 'longitude'), name='uniq_telemetry_device_ts_lat_lon')],
            },
        ),
    ]
