# Generated by Django 5.1.15 on 2026-08-22 16:52

import apps.tracking.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_trackingdevice_firmware_version_trackingdevice_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_type', models.CharField(choices=[('PING', 'Ping'), ('REQUEST_LOCATION', 'Request Location'), ('REBOOT', 'Reboot'), ('SET_REPORTING_INTERVAL', 'Set Reporting Interval'), ('CUSTOM', 'Custom')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=15)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=apps.tracking.models._default_max_retries)),
                ('last_error', models.TextField(blank=True, default='')),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='tracking.trackingdevice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='tracking_de_device__a9ac64_idx'), models.Index(fields=['status', 'created_at'], name='tracking_de_status_94dc2e_idx'), models.Index(fields=['status', 'expires_at'], name='tracking_de_status_814050_idx')],
            },
        ),
    ]
