# Generated by Django 5.1.15 on 2026-09-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('tracking', '0003_devicecommand'),
        ('vehicles', '0002_vehicle_last_service_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtelemetryevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.client'),
        ),
        migrations.AddField(
            model_name='rawtelemetryevent',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='rawtelemetryevent',
            index=models.Index(fields=['client', 'received_at'], name='tracking_ra_client__a9f768_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryevent',
            index=models.Index(fields=['client', 'timestamp'], name='tracking_te_client__33251d_idx'),
        ),
    ]
