# Generated by Django 5.1.15 on 2026-09-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_commssyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecurrenttelemetry',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Human-readable address of the latest position (from the comms current_table, when provided).', max_length=255),
        ),
    ]
