# Generated by Django 5.1.15 on 2026-09-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_vehiclecurrenttelemetry_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecurrenttelemetry',
            name='gps_odometer',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='GPS trip odometer in km (comms current_table.gpsodometer, reported in metres).', max_digits=12, null=True),
        ),
    ]
