# Generated by Django 5.1.15 on 2026-10-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_vehiclecurrenttelemetry_gps_odometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecurrenttelemetry',
            name='main_power',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Main (external) power voltage in V (comms mainpower = externalvoltage / 1000); 0 = disconnected.', max_digits=6, null=True),
        ),
    ]
