# Generated by Django 5.1.15 on 2026-10-04 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofences', '0001_initial'),
        ('vehicles', '0006_vehicle_idle_alert_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geofence',
            name='notify_on_enter',
        ),
        migrations.RemoveField(
            model_name='geofence',
            name='notify_on_exit',
        ),
        migrations.AddField(
            model_name='geofence',
            name='geofence_type',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('SPEED_LIMIT', 'Speed Limit')], db_index=True, default='ENTRY', max_length=15, verbose_name='Geofence type'),
        ),
        migrations.AddField(
            model_name='geofence',
            name='polygon',
            field=models.JSONField(blank=True, default=list, help_text='Polygon vertices [[lat, lon], ...] (polygons only).'),
        ),
        migrations.AddField(
            model_name='geofence',
            name='shape',
            field=models.CharField(choices=[('CIRCLE', 'Circle'), ('POLYGON', 'Polygon')], default='CIRCLE', max_length=10),
        ),
        migrations.AddField(
            model_name='geofence',
            name='speed_limit_kmh',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Speed Limit geofences only: alert when an assigned vehicle inside goes faster than this.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='Speed limit (km/h)'),
        ),
        migrations.AddField(
            model_name='geofence',
            name='vehicles',
            field=models.ManyToManyField(blank=True, help_text='Only assigned vehicles are monitored against this geofence.', related_name='geofences', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='geofence',
            name='radius_meters',
            field=models.PositiveIntegerField(help_text='Radius in meters, minimum 50 (polygons: enclosing radius).'),
        ),
    ]
