# Generated by Django 5.1.15 on 2026-10-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofences', '0002_geofence_types_shapes_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofence',
            name='geofence_type',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('SPEED_LIMIT', 'Speed Limit'), ('ENTRY_AND_EXIT', 'Entry and Exit')], db_index=True, default='ENTRY', max_length=15, verbose_name='Geofence type'),
        ),
    ]
