# Generated by Django 5.1.15 on 2026-10-03 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_vehicle_events'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='alert',
            field=models.ForeignKey(blank=True, help_text='The alert event this notification announces (panic popup + sound in the bell).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='alerts.alert'),
        ),
    ]
